### ISSUE TITLE
Microsoft MSAGL GraphViewerGDI problems

### ISSUE THREAD

**Issue by sgarg7** [daveaglick/LINQPad.CodeAnalysis#9]
When I get the package from Nuget, first I get the error  

> Could not load file or assembly 'Microsoft.Msagl.GraphViewerGdi, Version=3.0.0.0

When I get that project built and added to references, I get the error 

> Method not found: 'Void Microsoft.Msagl.GraphViewerGdi.GViewer.set_EdgeInsertButtonVisible(Boolean)

How can I get the version of GraphViewerGdi that is used by this project?

**Comment by daveaglick** [comment]
You shouldn't have to obtain or build anything extra. This is the first version to use external dependencies that aren't also NuGet packages and it looks like they didn't get included. I'll get a fix out ASAP - watch for a new version in NuGet shortly. Thanks for reporting this.

**Comment by daveaglick** [comment]
Sorry for the confusion. Try v1.2.1-rc1 which is now available in NuGet. Should fix the problem. Thanks again.
